### ISSUE TITLE
Refaktorisera booleans

### ISSUE THREAD

**Issue by einarpersson** [FelixLindblad/blackjack#3]
Noterade en sak du kunde refaktorisera:

```
def is_bust(hand):
    
    total = sum(hand)
    if total > 21:
        return True
    return False
```
till
```
def is_bust(hand):
    total = sum(hand)
    return total > 21
```

Dessa rader gör exakt samma sak. `total > 21` blir `True` eller `False` så du kan returnera det direkt, istället för att använda en if-sats som mellansteg. Hänger du med?

Du kan ändra denna och göra samma sak med funktionen `is_blackjack`

**Comment by FelixLindblad** [comment]
Ändrat!
