### ISSUE TITLE
Ta bort överflödiga returns

### ISSUE THREAD

**Issue by einarpersson** [FelixLindblad/blackjack#4]
Funktionerna `print_intro`, `result_of_this_game` och `final_result` behöver inte returnera `False` då detta ändå inte används någonstans i koden. Syftet med dessa funktioner är ju bara att skriva ut saker på skärmen (s.k. sidoeffekt), inte att returnera något resultat till den som kallar på funktionen.

Så du borde bara kunna ta bort `return False` för dessa funktioner

PS. [What is a side-effect?](https://softwareengineering.stackexchange.com/questions/40297/what-is-a-side-effect)

**Comment by FelixLindblad** [comment]
Ändrat!
